/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT4_FTM2CH0SRC_FTM 0x00u /*!<@brief FTM2 channel 0 input capture source select: FTM2_CH0 signal */

/*! @name PORTA10 (coord M9), PWM_2ch0
  @{ */
#define BOARD_INITPINS_PWM_2ch0_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_PWM_2ch0_PIN 10U    /*!<@brief PORTA pin index: 10 */
                                           /* @} */

/*! @name PORTA11 (coord L9), PWM_2ch1
  @{ */
#define BOARD_INITPINS_PWM_2ch1_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_PWM_2ch1_PIN 11U    /*!<@brief PORTA pin index: 11 */
                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
